/**
 * Maze Chunks - 4 different 8x8 chunk configurations
 * Each chunk has a color (for DEBUG visualization) and cell definitions
 * Each cell defines which walls it has: {top, left, bottom, right}
 */

const MAZE_CHUNKS = [
    // CHUNK 0: Open corridors with some walls
    {
        color: '#1a3a1a', // Dark green
        cells: [
        [{top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}],
        [{top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}]
    ]
    },
    
    // CHUNK 1: Maze-like with more walls
    {
        color: '#2a1a2a', // Dark purple
    cells: [
        [{top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: true, left: true, bottom: false, right: true}, {top: true, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}],
        [{top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}]
    ]
   },
    
    // CHUNK 2: Dense maze
    {
        color: '#1a1a3a', // Dark blue
        cells: [
        [{top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: true}],
        [{top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}],
        [{top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}],
        [{top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}]
    ]
    },
    
    // CHUNK 3: Sparse with wide corridors
    {
        color: '#3a2a1a', // Dark brown
                cells: [
        [{top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}],
        [{top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}],
        [{top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: true, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}]
    ]
    },

    // CHUNK 4 :something else
    {
        color: '#808000', // Dark brown
        cells: [
        [{top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: false, right: false}],
        [{top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}],
        [{top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: true}],
        [{top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}],
        [{top: false, left: false, bottom: false, right: false}, {top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}],
        [{top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: false, right: false}],
        [{top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}]
    ]
    },

    // CHUNK 5 :something else
    {
        color: '#008080',
        cells: [
        [{top: false, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: true, right: false}],
        [{top: true, left: false, bottom: false, right: false}, {top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}],
        [{top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: false, right: false}],
        [{top: true, left: true, bottom: false, right: false}, {top: true, left: false, bottom: false, right: true}, {top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: false, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: false, right: true}],
        [{top: false, left: true, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}, {top: true, left: true, bottom: false, right: false}, {top: false, left: false, bottom: false, right: true}, {top: true, left: true, bottom: false, right: true}, {top: true, left: true, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: true}],
        [{top: true, left: false, bottom: false, right: false}, {top: false, left: false, bottom: true, right: false}, {top: false, left: false, bottom: true, right: true}, {top: false, left: true, bottom: false, right: false}, {top: false, left: false, bottom: false, right: false}, {top: true, left: false, bottom: true, right: false}, {top: true, left: false, bottom: true, right: false}, {top: false, left: false, bottom: false, right: false}]
    ]
    }


];

// Constant for chunk size
const CHUNK_SIZE = 8;

// Expose to global scope for chunk designer
window.MAZE_CHUNKS = MAZE_CHUNKS;
